### ISSUE TITLE
qiime1 question

### ISSUE THREAD

**Issue by mavino** [mikerobeson/make_SILVA_db#4]
Not really an issue, just a question since I am pretty new to this field...
after having run all your pipeline to generate qiime1 compatible SILVA138 files, I need to run pick_otus.py in qiime1.
Would I use the files "SILVA_empv4_consensus_taxonomy.txt" as assign_taxonomy:id_to_taxonomy_fp and  "SILVA_empv4_emptyrem_derep.fasta" as assign_taxonomy:reference_seqs_fp?
Thank you very much

**Comment by mikerobeson** [comment]
Hi @mavino,

>Would I use the files "SILVA_empv4_consensus_taxonomy.txt" as assign_taxonomy:id_to_taxonomy_fp and "SILVA_empv4_emptyrem_derep.fasta" as assign_taxonomy:reference_seqs_fp?

Yes, that looks correct.

Note that this repository has been deprecated in favor of [RESCRIPt](https://github.com/mikerobeson/RESCRIPt) as highlighted in the README. I'd recommend using that tool, as it is much easier to download and manipulate the files as you'd like. *There are more improvements to come!* In fact, I'd also recommend switching over to [QIIME 2](https://qiime2.org/) as [QIIME 1](http://qiime.org/) has not been supported since Jan 2018.

**Comment by mavino** [comment]
Thank you so much for the quick reply...
waiting to move on qiime2 so I could use RESCRIPt...
Best.
